### ISSUE TITLE
Move common code from number-play to number-suite-common

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-suite-common#1]
Since we split part of Number Play into Number Compare, and there will be at least one more sim in the "Number Suite" (Number Pairs), I created number-suite-common for code that will be shared by at least two of these sims. I've been working on splitting this out and will push my first set of changes now.

**Comment by chrisklus** [comment]
@marlitas and I are going to finish this issue off tomorrow (just have some strings to move over) and then complete https://github.com/phetsims/number-suite-common/issues/2 next.

**Comment by chrisklus** [comment]
Final changes committed above, I think this issue is complete. Closing.

**Comment by zepumph** [comment]
Uh oh, one more spot where we are importing from number-play in number-compare. I updated the TODO to point here.

**Comment by chrisklus** [comment]
Thanks @zepumph! I cleaned up some query parameters in the above commits. I no longer see any usages of number-play or numberplay in Number Compare and vice-versa. TODO removed, I think this work is complete! Closing.
