### ISSUE TITLE
Remove spinners in Lab screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#11]
In https://github.com/phetsims/number-suite-common/issues/3, I suggested:

> - [ ]  UX would be more consistent if we get rid of spinners in Lab screen. Combine 4 object types into 1 toolbox. (effort: probably less than having to figure out where to place objects initially when spinner up-arrow is pressed)

@amanda-phet replied:

> Having no spinners seems inconsistent with the Ten, Twenty, and Compare screens, which is the main reason why the Lab screen has spinners. We are using them in this sim due to the age level of users and the potential for having trouble dragging objects quickly.

**Comment by pixelzoom** [comment]
@amanda-phet I'm not convinced about the need for consistency with the other screens, but would like to hear more.

A few thoughts...

(1) Consistency with the other screens DOE NOT seem relevant here, because the other screens are not about unconstrained free-form "play".   Position of the objects in the Lab screen is important and is fundamental to what the user is trying to build. That's not the case in the other screens.

(2) Consistency of interaction with all object types DOES seem relevant in this screen. If it's important to have a spinner for some objects, why is it not important to have spinners for _ALL_ objects?  If users indeed have "trouble dragging objects quickly", why is that not a problem for the objects that don't have spinners?

(3) When using the spinner "up" button, what does placing objects in some inital position achieve?  Since the user is going to be building something free form, we have no idea what a useful initial position is, and they will still need to drag the object to the desired place.  If they can drag it to the desired place, why can't they drag it out of the toolbox? 

(4) It's going to be a significant amount of work to figure out how/where to place objects when using the up arrow.  And as I said in (3), wherever we initially position the object is highly unlikely to be the desired location for what the student is trying to build.

(5) When using the spinner "down" button, we're removing the most-recently-created object that was placed in the play area.  In a "free play" situation, that's often not the object that I want to remove from the play area. I'm going to be frustrated when some object is removed that I didn't intend to remove.  And I still need to use drag-and-drop to return any object other than the most-recently-created object to its toolbox.  So the spinner down button has very limited usefulness in this screen.

Let's discuss.

**Comment by chrisklus** [comment]
I agree with the reasons in https://github.com/phetsims/number-suite-common/issues/11#issuecomment-1371519511 that the spinners should be removed. Consistency across the Lab screen seems nicest.

>When using the spinner "down" button, we're removing the most-recently-created object that was placed in the play area.

Not super relevant to the point in (5), but wanted to note that the "down" button removes the closest object, not the most recently created.

**Comment by pixelzoom** [comment]
> > When using the spinner "down" button, we're removing the most-recently-created object that was placed in the play area.
>
> Not super relevant to the point in (5), but wanted to note that the "down" button removes the closest object, not the most recently created.

Yikes -- I hadn't noticed that.  My initial few interactions with the sim happened to remove the last thing added (because they were closest), so I inteferred incorrectly, and was really confused after that.  Removing the last object added is typical, more easily-inferred, and more LIKELY to be inferred.  The current behavior is confusing since the positioning of the objects is random, but sometimes you DO remove the last object added because it happens to be closest. 

What's the reason for removing the closest object added, rather than the last object added? If there's no pedagocial reason, I recommend changing the behavior. (Maybe this deserves another GitHub issue.)

This also feels like another argument for removing the spinners in the Lab screen.  The down button on the spinner is only going to be useful if (a) I _know_ that the closest object will be removed, and (b) I _want_ the closest object to be removed.

**Comment by ariel-phet** [comment]
@pixelzoom @amanda-phet @chrisklus 

I strongly agree with @pixelzoom here. My recollection is that the lab screen is in particular modeled off of the lab screen in our fractions sims, which were actually popular with teacher for demonstrations/number talks. So I think there are multiple good arguments for getting rid of the spinners.

1. I don't think this screen is really about "dragging objects out quickly" it is about making connections between objects, numbers, and comparisons. I think speed is not an issue here. Whereas on the other screens, I do agree the spinners help support the goals and the connections trying to be made. Here a deliberate interaction that is slower is not a problem.

2. As @pixelzoom pointed out, removing the spinners would keep the interaction of all objects on this screen consistent, as in a simple drag.

3. Removing spinners will **vastly** simplify the sim code, the potential for bugs, QA testing. If only for the sake of expediency, I think removing the spinners is wise on the grounds of pure practicality. Removing them will massively reduce the QA burden of this sim (as there are so many corner cases with how objects are placed/removed from the play area -- sure to cause some sneaky bugs that will be expensive to identify, trace, and fix). If getting the sim out the door is a consideration (which in my opinion it should be), I think that argument alone is worth the removal of this feature on this screen.

**Comment by amanda-phet** [comment]
Discussed 1/5/23 

Since a number of items on the Lab screen have "grab and drag" we don't see a reason to only have spinners on the objects! 

Plus there are lots of good reasons to keep the code simple. 

Please go ahead and remove the spinners.

**Comment by pixelzoom** [comment]
In the above commit, I hid the spinners in the Lab screen, and added a bit more xMargin so that the "creator panels" look nice.  See screenshot below. @chrisklus feel free to have a look at the commit.

I also took a quick look at putting all of the objects in one HBox, inside one Panel.  That was relatively easy.  The harder part is that we’ll need to add transforms between the ScreenView and HBox coordinate frames, so that the objects know where their “creator panel” actually is.  @chrisklus and I are going will put this on our pairing list for Monday 1/8.

<img width="1004" alt="screenshot_2117" src="https://user-images.githubusercontent.com/3046552/210900793-d6dc1445-124b-412e-8460-50aa5a16f269.png">

**Comment by amanda-phet** [comment]
This looks nice to me!

**Comment by pixelzoom** [comment]
@chrisklus and I investigated combining the counting objects (dog, apple, butterfly, beachball) into one panel.   Something like this in LabScreenView.ts:

```typescrupt
const countingObjectsBox = new HBox( {
   children: [ this.dogPlayAreaNode, this.applePlayAreaNode, this.butterflyPlayAreaNode, this.ballPlayAreaNode ],
   ...
} );
const countingObjectPanel = new Panel( countingObjectsBox, {
  ...
} );

const bottomBox = new HBox( {
  children: [ this.tenFrameCreatorPanel, countingObjectPanel, this.onesPlayAreaNode ]
} );
this.addChild( bottomBox );
```



It would be a big change. It's assumed that these Nodes are in the same coordinate from as the ScreenView, and many things would need to change to handle coordinate-frame transforms.   So while we'd like to have these things in the same panel, it's mainly an aesthestic consideration, has little/no impact on usability, and is therefore not relevant to getting this sim published.

Since we previously established (in design meeting) that combining panels is not required, and @amanda-phet said "This looks nice to me!", we'll consider this work "done" and close this issue.
