### ISSUE TITLE
Handle backup strings for second language

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-suite-common#13]
Because we are manually getting strings for the second language, like:

```js
numberPlaySecondaryStrings[ `${NUMBER_PLAY_STRING_KEY_PREFIX}${stringKey}` ];
```

The sim crashes if the second language is missing a desired string key instead of gracefully filling in the English value like normal.

**Comment by chrisklus** [comment]
Adding blocks-sim-publication label to indicate this should be completed before starting dev testing

**Comment by pixelzoom** [comment]
@chrisklus I believe that I've addressed this in the above commit. Please review, close if OK.

**Comment by chrisklus** [comment]
@marlitas and I reviewed and made some changes in the above commits to support handling backup strings in number-compare as well, and then @pixelzoom @marlitas and I reviewed those changes together. I think we are set here, closing!
