### ISSUE TITLE
Support for dynamic locale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#2]
Eventually we want to add `supportsDyamicLocale: true` to package.json, then run `grunt modulify` to remove static strings from Strings.ts.   But the sims currently are using some static strings, notably in NumberPlayConstants.ts.   There's some work to do there related to text and speech synthesis.

**Comment by pixelzoom** [comment]
@chrisklus and @marlitas are going to do this after finishing #1.

**Comment by chrisklus** [comment]
I finished this off in the above commits (changes were independent of finishing #1). I opened https://github.com/phetsims/number-suite-common/issues/9 as a side issue of a remaining problem to investigate. Closing.
