### ISSUE TITLE
`NumberSuiteCommonStrings` Properties are not updated when locale changes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#20]
Put this at the end of number-play-main.ts:

```typescript
  NumberPlayStrings.wordStringProperty.link( word => {
    console.log( `word=${word}` );
  } );
  NumberSuiteCommonStrings.languageStringProperty.link( language => {
    console.log( `language=${language}` );
  } );
```

Then change Localization preference. 

You'll see that `NumberSuiteCommonStrings.languageStringProperty` is not updated. So it seems that `NumberSuiteCommonStrings` Properties are not being updated when locale changes. This affects the first-language label on LocaleSwitch, the title of LabScreen, and probably other things.

Assigning to @marlitas and @chrisklus, since they are working on other i18n issues.

**Comment by chrisklus** [comment]
@marlitas @zepumph and I addressed this in the above commit. We just had to copy the translated string files over to a new directory in babel called `number-suite-common`. The remaining work of removing duplicates is being tracked in https://github.com/phetsims/number-suite-common/issues/27. Closing.
