### ISSUE TITLE
Factor out string for i18n

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-suite-common#26]

**Comment by pixelzoom** [comment]
@zepumph No one is assigned and there's no information here abpout what string should be factored out. Please provide a description.

**Comment by pixelzoom** [comment]
This issue was apparently created to associate with this TODO in NumberSuiteCommonPreferencesNode.ts:

```
    // TODO: factor out this string if we like this, https://github.com/phetsims/number-suite-common/issues/26
    const loadAllHtmlText = new RichText(
      'To display a second language, run the <a href="{{url}}">“all” version</a> of Number Play.', {
```

Please don't create GitHub issues with no description.  It wastes people's time.

**Comment by pixelzoom** [comment]
Move to https://github.com/phetsims/number-suite-common/issues/28
