### ISSUE TITLE
"number-play.title" does not belong in number-suite-common-strings_en.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#31]
The title for the Number Play sim definitely does not belong in number-suite-common-strings_en.json:

```
  "number-play.title": {
    "value": "Number Play"
  },
```

**Comment by pixelzoom** [comment]
The title is duplicated in number-play-strings_en.json:

```
  "number-play.title": {
    "value": "Number Play"
  },
```

**Comment by pixelzoom** [comment]
This was easy to address, see above commit.  @chrisklus please review.

**Comment by chrisklus** [comment]
Thanks @pixelzoom, just another mistake from https://github.com/phetsims/number-suite-common/commit/3efd6108990b1e17387b517928e0f23e0fb27640. Closing.
