### ISSUE TITLE
number-suite-common-strings_en.json contains strings that are not "common"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#32]
These screen names do not belong in number-suite-common-strings_en.json.  They are specific to number-play.

```
  "screen.ten": {
    "value": "Ten"
  },
  "screen.twenty": {
    "value": "Twenty"
  },
  "screen.game": {
    "value": "Game"
  },
```

**Comment by pixelzoom** [comment]
Looking at the other strings in number-suite-common-strings_en.json, the problem is not just the screen names. There are a lot of strings in here that are not common, and are used only by number-play.

Strings that are specific to (used only by) number-play or number-compare should be moved to the string file for those repos.

**Comment by chrisklus** [comment]
Thanks @pixelzoom, this is the result of me being a blockhead in https://github.com/phetsims/number-play/commit/a42135958aead021994bc12888b0337f8d7e11b4 and https://github.com/phetsims/number-suite-common/commit/3efd6108990b1e17387b517928e0f23e0fb27640.

**Comment by chrisklus** [comment]
Fixed in the above commits, closing.
