### ISSUE TITLE
Preferences view needs cleanup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#36]
Noted while working on https://github.com/phetsims/number-suite-common/issues/35...

NumberSuiteCommonPreferencesNode, NumberPlayPreferencesNode, and NumberComparePreferencesNode all need major cleanup. There are multiple controls being created in the constructor, and they are not properly encapsulated.   This will be trouble for future maintenances and PhET-iO instrumentation. 

Self assigning.

**Comment by pixelzoom** [comment]
The above commits will look like major changes. But what I did (in a nutshell) was to factor out a class for each control that appears in the Preferences dialog.  So we now have these classes, whose names match their labels:

* SecondLanguageControl
* ShowOnesControl
* SubitizeTimeControl

@chrisklus please review. Close if OK.

**Comment by chrisklus** [comment]
Thanks @pixelzoom, I really like these changes. I tested all the enabled-ness combinations and control functions. Closing.
