### ISSUE TITLE
Issues with SecondLocaleSelectorCarousel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#37]
Notes while working on https://github.com/phetsims/number-suite-common/issues/36 ...

There are a couple of significant problems with SecondLocaleSelectorCarousel:

(1) It's name. The titme of the control is "Second Language", not "Second Locale".  This will become a problem when this code is eventually instrumented for PhET-iO, because the convention is to name things based on the name that you see in the UI.

(2) For some reason, SecondLocaleSelectorCarousel chunks the languages into a set of GridBoxes, each with 10 rows. It then displays 1 Grid at a time.  This is totally unnecessary, duplicating the responsibility of Carousel.

```
     // A prototype where we show all languages in grid managed by a Carousel so that there aren't too many items
    // displayed at one time
    const chunkedLocaleItems = _.chunk( createInteractiveLocales(), 10 );
    const carouselItems = chunkedLocaleItems.map( localeItem => {
      return new GridBox( {
        xMargin: 5,
        yMargin: 3,
        xAlign: 'center',
        autoRows: 10,
        children: [ ...localeItem ],
        resize: false
      } );
    } );
```

**Comment by pixelzoom** [comment]
In the above commit, SecondLocaleSelectorCarousel was absorbed into SecondLanguageControl.  It's greatly simplified, and no longer requires a subclass, see below.  @chrisklus please review, close if OK.

```typescript
    // Carousel for choosing the second language.
    const carouselItems = localeProperty.validValues!.map(
      locale => new LanguageSelectionNode( secondLocaleProperty, locale ) );
    const secondLanguageCarousel = new Carousel( carouselItems, {
      visibleProperty: showSecondLocaleProperty,
      itemsPerPage: 10,
      spacing: 6,
      margin: 5,
      orientation: 'vertical'
    } );
```

**Comment by pixelzoom** [comment]
Also note the problem reported and addressed in:
*  https://github.com/phetsims/number-suite-common/issues/38

**Comment by chrisklus** [comment]
Thanks @pixelzoom, that's much simpler. I like that the accordion box stays full-height when there are few language options too. Closing.

**Comment by pixelzoom** [comment]
Reopening:

@chrisklus said:
> ...  I like that the accordion box stays full-height when there are few language options too.

I finally undersand what you meant by this. When I ran with `locales=es,en`, I saw this:

<img width="463" alt="screenshot_2233" src="https://user-images.githubusercontent.com/3046552/215926472-8cf53d22-27bf-4185-9a12-7159d9f850f9.png">

That looks really wrong, and I'm sort of surprised that Carousel behaves that way.  And I see no good reason to a single-page Carousel with lots of empty cells.

So in the above commit, I fixed the options passed to Carousel:

```diff
- itemsPerPage: 10,
+ itemsPerPage: Math.min( 10, carouselItems.length ),
```

That results in this for `locales=en,es,fr`:

<img width="474" alt="screenshot_2231" src="https://user-images.githubusercontent.com/3046552/215926703-5994b5a7-4308-4bd0-9bdb-8b1707c4925c.png">


And this for `locales=*`:

<img width="434" alt="screenshot_2232" src="https://user-images.githubusercontent.com/3046552/215926689-211c6ed3-6eaa-4524-adbb-5a78d86e0b71.png">

@chrisklus please review, close (again) if OK.
