### ISSUE TITLE
Second Language carousel does not show initial selection

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#38]
If you run with `?locales=*`, then the Second Language control does not show you the value that is initially selected.  For example:

1. Run Number Play with `?locales=*`
2. Press the Preferences button
3. Got to the Simulation tab in the Preferences dialog
4. Turn on the "Second Language" toggle. You'll see this, note that the initial selection for second language is not visible:

<img width="463" alt="screenshot_2183" src="https://user-images.githubusercontent.com/3046552/213940488-a750b04b-7d76-4221-be9c-1192c750c0f9.png">

The correct behavior is for the carousel to show that English is the initial selection, like this:
<img width="458" alt="screenshot_2184" src="https://user-images.githubusercontent.com/3046552/213940547-27bc1cd2-089e-45d6-b085-75920ddbb270.png">

**Comment by pixelzoom** [comment]
Fixed in the above commits. @chrisklus please review. Close if OK.

**Comment by chrisklus** [comment]
Commits look good and it's functioning as expected, thanks @pixelzoom. Closing.
