### ISSUE TITLE
References to "bucket"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#39]
There are 22 references to "bucket" (case insensitive) in number-suite-common and number-play.  13 are in code constructs, 9 are in comments. There are no buckets in these sims.   This is confusing, so let's change "bucket" to the correct word for where a counting object originates.

**Comment by pixelzoom** [comment]
I don't feel that this issue is blocking publication.

**Comment by zepumph** [comment]
instead of "bucket" let's call it "creator node" or "creatorNode" or perhaps "counting creator node" in some cases.

This cleanup doesn't block, but we still may get to it before publication. Noting https://github.com/phetsims/number-suite-common/issues/29 as a superset of this.
