### ISSUE TITLE
Issues with CountingPlayArea

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#40]
Mutliple issues with CountingPlayArea.ts:

(1) First there's the name "CountingPlayArea".... The term "play area" means something specific in PhET sims, and is used here to mean something entirely different. That's very confusing -- it's been consfusing me non-stop when reading the code.   Please change the name to something else.  

(2) The documentation at the top of the file is totally bogus, it was copied from elsewhere. There's no Explore screen in any of the number-suite sims.

```
/**
 * Model for the Explore screen in Make a Ten. Includes the total, cues, and adding in initial numbers. This file was
 * copied in part from make-a-ten/explore/model/MakeATenExploreModel.js
 * then modified by @chrisklus to be used in number-play.
 ```

(3) What is a "play object"?  Is it a "counting object", the term that is use elsewhere.

```
// the minimum distance that a playObject added to the play area via animation can be to another playObject in the
// play area, in screen coordinates
const MIN_DISTANCE_BETWEEN_ADDED_PLAY_OBJECTS = 60;
```

**Comment by pixelzoom** [comment]
I don't feel that this issue is blocking publication.

**Comment by zepumph** [comment]
I showed @chrisklus the PDOM of a sim with interactive description and we agree it seems very overloaded. 

- [x] We would like to rename `CountingPlayArea` to `CountingArea`. (multiple types, lots of searches like "play area" in the number suite project too.
- [x] @chrisklus will update the doc for (2)
- [x] rename `play object` to `countingObject`

**Comment by zepumph** [comment]
Also tagging general TODOs over in https://github.com/phetsims/number-suite-common/issues/29

**Comment by chrisklus** [comment]
This issue is complete, closing!
