### ISSUE TITLE
Primary locale toggle switch label no updating

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-suite-common#42]
While working on https://github.com/phetsims/number-suite-common/issues/13 @chrisklus and I noticed that the toggle switch label for the primary local would not update when the primary locale was changed.

**Comment by marlitas** [comment]
I added a link to the localeProperty so that the toggleSwitch label is updated accordingly. @chrisklus over to you for review and closing.

**Comment by chrisklus** [comment]
Awesome, thanks! Looks great. I set the initial value to the empty string above to match the secondLanguageText to remove a duplicated line since they're handled in the link. Closing!
