### ISSUE TITLE
Hide irrelevant preferences controls,  instead of disabling them

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#43]
Depending on the value of the `screens` query parameter, some Preferences controls are not relevant.  They are currently disabled.  In our dev-testing party today, @chrisklus @marlitas and I decided that it makes more sense to hide irrelevant controls, rather than disable them.

**Comment by pixelzoom** [comment]
@chrisklus also noted that ReadAloudControl needs to be changed to use `NumberSuiteCommonPreferencesNode.hasScreenType`.

Done in the above commit. Over to @chrisklus to review.

**Comment by chrisklus** [comment]
Code looks great and functionality is working well, thanks! Closing.
