### ISSUE TITLE
Yellow megaphone should grey out when Audio Features toggle = false

### ISSUE THREAD

**Issue by marlitas** [phetsims/number-suite-common#45]
When you disable audio features in the preferences dialog a user can still press the yellow megaphone button, but nothing happens. Seems strange and undesirable. Would be better to grey this button out. 
![Screenshot 2023-01-31 at 4 01 40 PM](https://user-images.githubusercontent.com/42476338/215911977-72129c05-7d27-42f6-9d06-ccffb0bd3ac8.png)

**Comment by pixelzoom** [comment]
I'll take this one.

**Comment by pixelzoom** [comment]
Addressed in the above commit. @chrisklus please review, close if OK.

**Comment by chrisklus** [comment]
Working great, thanks @pixelzoom. Closing.
