### ISSUE TITLE
Please test carousel functionality

### ISSUE THREAD

**Issue by samreid** [phetsims/number-suite-common#48]
In https://github.com/phetsims/sun/issues/814 significant changes to the carousel were merged to master, including some commits in number-suite-common.  Please test for any regression errors.  I have tested the basic functionality in the lab screen and I do not see obvious errors.  But I thought it would be good to call for some explicit testing if there are corner cases I'm missing.  I see @chrisklus and @amanda-phet names on the project board, so I'll assign to them.  Thanks!

Also, I wasn't sure whether to make this issue here or in counting-common.  Please feel free to move, or close if all is well.

**Comment by pixelzoom** [comment]
Since we did our "self dev test" this past week, we should do this before publishing a dev version for QA.  So labeling as blocking.

**Comment by pixelzoom** [comment]
Carousel in the Lab screen seems to be working correctly.

"Second Language" Carousel in Preferences is working as expected with `?locales=*`.  But with a smaller number of locales, I'm seeing holes where the buttons would be, as reported in https://github.com/phetsims/sun/issues/828.  For example see screenshot below for `?locales=en,es`.    I doubt that this blocks publication, but it's ugly -- @amanda-phet, your call.

<img width="509" alt="screenshot_2271" src="https://user-images.githubusercontent.com/3046552/217031589-fa035ee5-8e0f-42de-a9b5-9b1c68d33954.png">

**Comment by amanda-phet** [comment]
I agree, it's not great, but it's also a rare situation because users won't be using that query parameter.

**Comment by chrisklus** [comment]
Thanks @samreid! Carousel is looking great on Number Play's end. Looks like the problems mentioned in https://github.com/phetsims/number-suite-common/issues/48#issuecomment-1419390817 were addressed over in https://github.com/phetsims/sun/issues/828, thanks @pixelzoom! Closing.
