### ISSUE TITLE
Voice for "espanol (Mexico)" is too fast

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/number-suite-common#50]
Also noted that the voice for "espanol (Mexico)" reads things super fast, like it's meant for screen reader.  Chrome 109 on macOS 13.2.

_Originally posted by @pixelzoom in https://github.com/phetsims/number-suite-common/issues/47#issuecomment-1421210233_
            

I doubt there is anything we can do about this, but lets try to reproduce and take a look at the voice rate just in case.

**Comment by jessegreenberg** [comment]
@chrisklus and I tried on macOS 12.6 Chrome 108 and the voice rate of "espanol (Mexico)" seemed reasonable. 

I tried on my machine and did not even have any "MX" voices, I only have "es-ES" and "es-US", so I wasn't able to test.

**Comment by pixelzoom** [comment]
> @chrisklus and I tried on macOS 12.6 Chrome 108 and the voice rate of "espanol (Mexico)" seemed reasonable.

Hmm.... This is odd. On Chrome 109 + macOS 13.2, the "espanol (Mexico)" voice is so fast that I can't understand it. Happy to give you a demo over Zoom.

**Comment by pixelzoom** [comment]
I demoed for @chrisklus on Zoom, and we agreed that "espanol (Mexico)"  is unusable on Chrome 109 + macOS 13.2 --- both of which are the latest versions.  It's probably behaving differently on macOS 12.6 Chrome 108 because those are older versions.    As @chrisklus said, this just demonstrates how we're unable to choose a usable voice, given a locale.

**Comment by jessegreenberg** [comment]
Yes, I totally believe it. 

> this just demonstrates how we're unable to choose a usable voice, given a locale.

That makes sense to me (related to #47).

Before closing maybe we should let design team know this can happen when using speech synthesis. Otherwise I don't think there's anything else for this issue, back to @chrisklus.

**Comment by chrisklus** [comment]
Thanks @jessegreenberg @pixelzoom. Marking on hold until decisions are made in https://github.com/phetsims/number-suite-common/issues/47.

**Comment by chrisklus** [comment]
Removing on-hold since #47 is complete.

@pixelzoom can you confirm that this fixes your fast voice issue? After Updating Chrome (110), I have Juan as the default and an additional voice Paulina for `es_MX`. Feel free to close if all set.

**Comment by pixelzoom** [comment]
👍🏻 closing.
