### ISSUE TITLE
Problems with SpeechSynthesisButton

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-suite-common#51]
Digging into https://github.com/phetsims/number-suite-common/issues/47 more is revealing some big problems with how much responsibility the SpeechSynthesisButton has, and the fact that there are two instances of it in Number Play. Responsibility for updating the voice should instead be in NumberSuiteCommonPreferences (if the toggle switch model Property is moved there) or NumberSuiteCommonSpeechSynthesisAnnouncer, and responsibility for speaking because of the readAloud=true preference should likely happen in NumberSuiteCommonSpeechSynthesisAnnouncer. Right now there is a problem that the sim reads aloud when readAloud=true and the voice changes, which is a nice feature, but that action can happen on screens that DON'T have speech synthesis features. And because the Twenty screen speaker button is instantiated after the Ten screen, performing this action while on the Ten screen (changing the language and hearing the number read), the Twenty screen number is read out instead of the Ten screen's. This is another symptom of (me doing a bad job of) mixing a global preference with screen-specific state. So, all of that needs to be moved to a global place instead of SpeechSynthesisButton. There, we can filter by screenProperty's value to determine what "state" to read aloud.

This was a big headache to investigate, but I think I have a good understanding of how to make it a lot better. And I've known for a while that SpeechSynthesisButton felt a little sketchy. I believe I told @jessegreenberg way back in causal discussion when I first developed these features that it felt like there should be a more global place that should be responsible for them, so I'm glad we have NumberSuiteCommonSpeechSynthesisAnnouncer to work with now.

UPDATE: Noting that a lot of this functionality was moved to a new file, NumberSuiteCommonUtteranceQueue.ts, instead of NumberSuiteCommonSpeechSynthesisAnnouncer.ts.

**Comment by chrisklus** [comment]
Completed in the commits above, thanks to help from @marlitas and @pixelzoom. @pixelzoom agreed to review these changes. This was a very invasive change, hitting about 20 files, but the main files to look at are:

* NumberCompareUtteranceQueue.ts
* NumberPlayUtteranceQueue.ts
* NumberSuiteCommonSpeechSynthesisAnnouncer.ts
* NumberSuiteCommonUtteranceQueue.ts
* SpeechSynthesisButton.ts

Noting for @pixelzoom that I tried passing in Properties like CompareModel.comparisonStringProperty into the initialize call in number-compare-main.ts to avoid duplicating Properties + the link on CompareModel.ts Line 73, but couldn't find a way so let me know if you see a better way than the pattern I'm using (same thing in Number Play).

Also noting that if you notice some unexpected behavior when using readAloud, I may have asked a question about it over in https://github.com/phetsims/number-suite-common/issues/52.

**Comment by pixelzoom** [comment]
Well done  - this looks great. It's a big improvement over the previous implementation.  

A few things to consider:

- [x] In all of the files identified in https://github.com/phetsims/number-suite-common/issues/51#issuecomment-1432545099, there's a lack of documentation for fields. Best to get in the habit of doing this as you go.

- [x] NumberSuiteCommonSpeechSynthesisAnnouncer could use some refinement related to `updateVoice`.  Specifically:
    * `updateVoice` can be private
    * Field `this.updateVoiceListener` is unnecessary. It's private, only used in 1 place, and never unlinked.
    * The `if ( initialized )` in `isInitializedProperty` listener seems redundant;  `updateVoice` checks `this.initialized`.  
    * There are 3 places where `updateVoice` is called. It looks to me like they could pulled together into 1 Multilink.

- [x] In SpeechSynthesisButton, replace `Multilink.multilink(...)` with `enabledProperty: new DerivedProperty(...)`.   The preferred pattern is to used `visibleProperty` and `enabledProperty` options where possible, rather than setting `this.visible` or `this.enabled` in a listener.

**Comment by chrisklus** [comment]
Thanks for reviewing @pixelzoom! Review comments look great, I addressed them in the above commits. I think we are all set to close here.
