### ISSUE TITLE
Should a user's voice preference for a locale persist?

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-suite-common#53]
When @marlitas and I were pairing on https://github.com/phetsims/number-suite-common/issues/47, @marlitas asked the question: When a user chooses a voice for a given locale (for primary or second language), if they choose a different locale and then come back to the first locale, should the voice they selected the first time be the default selection? Or should it just be the top voice like normal?

I personally don't think this is necessary, as it doesn't seem likely that a user will be changing the primary and second locale very much - ideally they will mostly be switching between the two. Even if a user does select new languages more often than we expect, there are usually fewer than 10 voices available, so it doesn't seem like that big of a hassle to reselect the voice that was in use previously. So I think I prefer the consistently of always choosing the top voice for a locale. That said, I can see how this feature could be nicer than the current behavior.

 Tagging @marlitas @amanda-phet @pixelzoom if anyone would like to weigh in.

**Comment by marlitas** [comment]
I personally think it would be frustrating if it doesn't save my previous choice, but not sure it's worth the dev effort. A scenario I can think of is:

1. Teacher goes through espanol voices and finds one they like
2. Teacher decides to also look through espanol( Mexico ) as well
3. Teacher likes other option better goes back to espanol
4. Teacher realizes voice changed and doesn't remember which one they landed on
5. Teacher has to go through voices again to find their top choice.

This is the first situation that comes to mind that could be potentially annoying for a user, but I think it's up to the rest of the team on wether this is enough of a nuisance to address in the code. @chrisklus may be able to provide more info on the dev time/effort to address this to provide more data on wether it's worth it or not.

**Comment by chrisklus** [comment]
Thanks @marlitas! I don't think it would be a huge effort, I'm guessing 1-2 hours to finish.

**Comment by amanda-phet** [comment]
I don't have an opinion either way. @pixelzoom this seems like something you'd probably be able to weigh in on.

**Comment by amanda-phet** [comment]
Actually, I have a slight preference toward doing nothing, so that we can finish this sim.

**Comment by pixelzoom** [comment]
+1 for doing nothing.  Remembering previous choices is a slippery slope - it can apply to all kinds of things in a sim. Imo it is (in general) an unnecessary development cost, for little-to-no benefit, and not something that users expect.   It's definitely not necessary for publication of this sim.

**Comment by chrisklus** [comment]
Great, thanks for everyone's feedback. Leaving assigned to @amanda-phet to defer or close.

**Comment by amanda-phet** [comment]
Thanks for weighing in @pixelzoom . I'm good with closing this. Glad to have it all documented in case we want to revisit this in the future.
