### ISSUE TITLE
Disable speech-synthesis button when relational operator checkbox is unchecked

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#6]
From https://github.com/phetsims/number-suite-common/issues/3:

> - [ ] In Number Compare, should the speech-synthesis button be disabled when the relational operator checkbox is unchecked? (effort: trivial)

@amanda-phet replied:

> Yes!

I'll knock this one off.

**Comment by pixelzoom** [comment]
Done in the above commits.  Note that this is relevant only for the Compare screen in Number Compare.  I tested with `?locales=en,es` to verify that the Multilink in SpeechSynthesisButton still works correctly.  @chrisklus want to review?  Close if it looks OK.

**Comment by chrisklus** [comment]
Change look great and behavior is working well on my end. Thanks @pixelzoom, closing.
