### ISSUE TITLE
Full bounds of CountingObject needed before view has been created

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-suite-common#65]
Promoting a TODO to an issue:

https://github.com/phetsims/number-suite-common/blob/01cd67c27a07d0dafbf27d46fc52e8519364edb7/js/common/model/CountingArea.ts#L168-L170

in `CountingArea.createCountingObjectFromCreatorNode`, we have some magic numbers and algorithm that is trying to guess at the size of the "handle" sticking out above the objects. We should try to remedy this with:

1. Ideally positioning logic resolving after we have a view
2. Share a constant between view and model at the very least.

**Comment by zepumph** [comment]
Promoted its own issue from https://github.com/phetsims/number-suite-common/issues/29

**Comment by chrisklus** [comment]
@zepumph and I were able to fix this in a nice way in the above commits. Closing!
