### ISSUE TITLE
Objects animating to a destination should be counted when determining position of next object

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-suite-common#66]
Promoting TODO to issue: 

https://github.com/phetsims/number-suite-common/blob/854f379e8017b2fbefa8bf57a03099858d8feac0/js/common/model/CountingArea.ts#L178-L181

Basically, we do want to include animating objects here, but only if their destination is out in the counting area (though caring about the ones heading to disposal shouldn't change anything). Right now we only care about already completed positions, so moving many out at once causes overlap.

Likely we need to store `CountingObject.destination` for use here.

**Comment by zepumph** [comment]
Promoted its own issue from https://github.com/phetsims/number-suite-common/issues/29

**Comment by zepumph** [comment]
@chrisklus and I got to a commit point, then @chrisklus had to leave and I made a couple more changes. @chrisklus anything else here for cleanup?

**Comment by chrisklus** [comment]
Commits look great, thanks for finishing this up @zepumph. Closing.
