### ISSUE TITLE
Number and Symbol cards return to incorrect location after window resize

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-suite-common#69]
Found while working on https://github.com/phetsims/number-play/issues/228.

Tagging https://github.com/phetsims/qa/issues/929.

If you pull out a number card or symbol card, then resize the window (in a way that moves the number card or symbol card home), then return them, they animate to the wrong spot. This is present in rc.1.

**Comment by chrisklus** [comment]
From 4/11 standup with @zepumph and @Nancy-Salpepi:

We are going to try converting the home location Vector2 to a function that gets the current position.

**Comment by zepumph** [comment]
@samreid @chrisklus and I fixed this by recalculating the destination when dropping, and animating to the side of the carousel if the card is off page. @Nancy-Salpepi can you please take this for a test drive since we discussed it this morning together? Resize should not cause this bug anymore on master.

**Comment by Nancy-Salpepi** [comment]
Cards now animate to the correct position when changing window size.
A couple of things I noticed: 
--If I place numbers to the left and right sides of the carousel and then decrease window size, the number on the left will not overlap the carousel, but the number on the right will.
-Operation cards can also overlap the Operations panel when decreasing window size. This didn't happen in dev.10. 


https://user-images.githubusercontent.com/87318828/231284789-798d9a65-ad6c-4ac9-a862-8955d6526f44.mp4




<img width="126" alt="Screenshot 2023-04-11 at 4 42 08 PM" src="https://user-images.githubusercontent.com/87318828/231284718-ece22ac7-090c-43d3-a6cd-d55504e7135d.png">

**Comment by chrisklus** [comment]
@Nancy-Salpepi @zepumph and I reviewed the last two behaviors identified in https://github.com/phetsims/number-suite-common/issues/69#issuecomment-1504072929, and think we are good to go as is. We though about making new bounds for all of the things on this screen to contain them to not overlap with any of the panels, but concluded that using their own drag bounds seems fine.

**Comment by zepumph** [comment]
We discussed this with @amanda-phet to review the new (3rd paradigm) for animating items back into the carousel. We decided to keep this in because the animation behavior is more important for the younger audience of this sim. It would be better than disappearing when dropped. We will proceed with cherry picking it.

**Comment by chrisklus** [comment]
Patch applied

**Comment by zepumph** [comment]
For QA: The expected, new behavior for this release is the the card will always return exactly to the location of that number's card, no matter the resize. If that card number's creator in the carousel is "off the page", then it will animate to the edge of the carousel in the direction of where the card's page would be (left or right), but not go beyond, and instead just to where the center of the card meets the edge of the carousel. 

Feel free to close if there is nothing too weird about this.

**Comment by Nancy-Salpepi** [comment]
This looks good to me in rc.2.
Closing
