### ISSUE TITLE
Unnecessary customizations of the Game status bar

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#7]
Related to https://github.com/phetsims/number-suite-common/issues/4 ...

There's currently a `ts-expect-error` in this piece of code in NumberPlayGameLevelNode.ts:

```typescript
    // color the backButton in the statusBar yellow and increase its touch area
    const backButton = statusBar.children[ 1 ].children[ 0 ];
    // @ts-expect-error TODO-TS: Open issue to expose backButton options in InfiniteStatusBar
    backButton.baseColor = Color.YELLOW;
    backButton.touchArea = backButton.bounds.dilated( NumberPlayConstants.TOUCH_AREA_DILATION );
    this.addChild( statusBar );
```

This code is changing the color and touchArea for the back button in the game's status bar.  And it's reaching deep inside `statusBar` to do so.

Two problems with this:

(1) The standard color for this button (and most buttons) is `PhetColorScheme.YELLOW`.  I see no reason why this sim should not be using that color.  If we think a different color should be used as the standard, that's a general discussion, not a reason to do so here.

(2) There is nothing about this specific use of the status bar that requires the button's touchArea to be dilated.  The default seem plenty big for touch.  If we do want to dialte the touchArea, it seems appropriate to do so for all sims, and that should be a general discussion.

So I'm going to remove this code, then assign to @amanda-phet for sign-off, or instructions on next steps.

**Comment by pixelzoom** [comment]
Customizations of the back button were deleted in the above commit.  Screenshot below shows the Game screen with `?showPointerAreas`.

@amanda-phet please review this change, feel free to close.  If you'd like to make general changes to the status bar (`InfiniteStatusBar`) please open an issue in vegas.

@chrisklus FYI.

<img width="1145" alt="screenshot_2108" src="https://user-images.githubusercontent.com/3046552/210465397-2c9f214b-ca3e-4bf2-8885-84b0eacdf74a.png">

**Comment by pixelzoom** [comment]
@amanda-phet If you do want to customize the back button in this way, estimated time is 30-60 minutes to (1) make changes to vegas.InfiniteStatusBar API, (2) update other affected sims, and (3) restore customizations in Number Play.

**Comment by amanda-phet** [comment]
I don't think this customization was intentional, to my knowledge. This all looks very reasonable to me.

**Comment by pixelzoom** [comment]
Great, thanks @amanda-phet.  @chrisklus if this is OK with you, feel free to close.

**Comment by chrisklus** [comment]
Yeah I know the touch area was expanded just because there's room, not sure why I changed the button color to something so similar. All set to close.
