### ISSUE TITLE
Add pointer areas also when adding touch areas (object creator nodes)

### ISSUE THREAD

**Issue by zepumph** [phetsims/number-suite-common#70]
Here we see that touch areas are looking really nice, but there aren't expanded pointer areas. Can we add that for a bit of a usability boost?
For both of these:

![image](https://user-images.githubusercontent.com/6856943/231268062-1c6941e0-82e0-459e-8925-aa22e90b990b.png)

![image](https://user-images.githubusercontent.com/6856943/231267990-9b43c7a8-f650-4200-bf04-be9564462163.png)

**Comment by zepumph** [comment]
And now: 

![image](https://user-images.githubusercontent.com/6856943/231269934-324b910c-0780-4d72-93ec-050382d6e457.png)

**Comment by chrisklus** [comment]
Patches applied above

**Comment by zepumph** [comment]
For QA: Mouse areas were dilated to match the touch areas, please make sure this doesn't cause any undo problems, and also enjoy the better user experience when pulling out non-card counting objects! Feel free to close if all is good.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2. Closing.
