### ISSUE TITLE
LocaleSwitch shifts left/right when labels are changed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#8]
While working on #4, I noticed that LocaleSwitch shifts left/right when its text labels are changed. This is because the labels need to be wrapped in an AlignBox to give them the same effect width.

**Comment by pixelzoom** [comment]
Fixed in the above commit.   Over to @chrisklus to review, close if OK.

To verify in master:

1. Run the sim with `?locales=en,es`
2. Go to Ten screen
3. Open Preferences dialog, Simulation tab
4. Turn on the "Second Language" toggle switch
5. Switch between "English" and "espanol" in the combo box. Observe that LocaleSwitch remains centered below the WordAccordionBox.

**Comment by chrisklus** [comment]
Thanks @pixelzoom, this is a nice change. Code looks good and working well for me locally. Closing.
