### ISSUE TITLE
numberToString is relying on NumberSuiteCommonStrings having non-dynamic string keys at runtime

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-suite-common#9]
Even with `"supportsDynamicLocale": true` enabled in this repo, NumberSuiteCommonStrings appears to still have non-dynamic string keys at runtime. This is currently still being relied on in `numberToString` in NumberSuiteCommonConstants, even while passing type checking:

```js
numberToString: ( numberPlaySecondaryStrings: IntentionalAny, number: number, isPrimaryLocale: boolean ): string => {
  const stringKey = NUMBER_TO_STRING_VALUE[ number ] as keyof typeof NumberSuiteCommonStrings;
  assert && assert( stringKey, `no stringKey found for number=${number}` );

  // TODO: This is relying on NumberSuiteCommonStrings having non-dynamic string keys at runtime. Is that okay?
  return isPrimaryLocale ? NumberSuiteCommonStrings[ stringKey ] :
         numberPlaySecondaryStrings[ `${NUMBER_PLAY_STRING_KEY_PREFIX}${stringKey}` ];
},
```

The hacky way around this is to add `"StringProperty"` to `stringKey` when getting values from `NumberSuiteCommonStrings`. Self assigning to investigate.

**Comment by marlitas** [comment]
We can look at this together this afternoon too @chrisklus.

**Comment by marlitas** [comment]
This was resolved in the above commit. Closing!
